site_name: GitGud Security Notes
site_url: https://notes.aldosimon.com
theme:
  name: material

markdown_extensions:
 - pymdownx.superfences:
     custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:pymdownx.superfences.fence_code_format
 - footnotes